components:
  aeroclub:
    entity: component
    title: Aeroclub
  aeroclub.applications:
    entity: component
    title: Applications
  aeroclub.applications.dictionaries:
    repository: aeroclub.platform.dictionaries
    title: Dictionaries Console
    entity: component
    project: Aeroclub Platform
    description:
    url:
    technologies:
    links:
      - id: aeroclub.services.dictionaries
        direction: -->
  aeroclub.applications.companies:
    repository: aeroclub.companies
    title: Companies & Profiles Console
    entity: component
    project: Aeroclub Companies
    description: Консоль для настроек компаний
    url: http://wiki.aeroclub.int/pages/viewpage.action?pageId=18580224
    technologies:
    links:
      - id: aeroclub.services.companies
        direction: -->
  aeroclub.applications.passport:
    repository: aeroclub.passport
    title: Passport
    entity: component
    type: Изменить
    project: Aeroclub Passport
    description: Предоставление данных для доступа к ресурсам
    url: http://wiki.aeroclub.int/display/PROJECTDOC/Passport
    technologies:
    links:
      - id: aeroclub.db.passport
        direction: -->
      - id: aeroclub.db.profiles
        direction: -->
        title: Аутентификация
  aeroclub.applications.time:
    repository: aeroclub.time
    title: Time
    entity: component
    project: Aeroclub Time
    description: Самостоятельное оформления услуг клиентами
    url: http://wiki.aeroclub.int/display/PROJECTDOC/Time
    technologies:
    links:
      - id: aeroclub.applications.timeNew
        direction: -->
  aeroclub.applications.time.backend:
    repository: aeroclub.time.backend
    title: Time Backend
    entity: component
    type: Удалить
    project: Aeroclub Time
    description:
    url: http://wiki.aeroclub.int/display/PROJECTDOC/SRV+Time.Api
    technologies:
    links:
      - id: aeroclub.applications.time
        direction: -->
      - id: aeroclub.db.cabinet
        direction: -->
      - id: aeroclub.services.businesstrips
        direction: -->
      - id: aeroclub.db.profiles
        direction: -->
      - id: aeroclub.services.dictionaries
        direction: -->
      - id: aeroclub.services.vault
        direction: -->
      - id: aeroclub.backgroundservices.indexer
        direction: -->
  aeroclub.integration.inAppStory:
    repository:
    title: InAppStory
    entity: component
    project:
    description: Сервис для отображение историй
    url: https://inappstory.ru/
    technologies:
